project_id = "bvezzatavermwhdlljyy"

[functions.sync-feegow]
verify_jwt = false

[functions.run-reconciliation]
verify_jwt = false

[functions.process-comprovante]
verify_jwt = false

[functions.import-ofx]
verify_jwt = false

[functions.sync-getnet]
verify_jwt = false

[functions.feegow-update-prices]
verify_jwt = false

[functions.import-getnet-csv]
verify_jwt = false

[functions.feegow-healthcheck]
verify_jwt = false

[functions.feegow-backfill]
verify_jwt = false